TransparentPath/buildly-react-template

src/App.js
src/midgard/components/Alerts/Alerts.js
src/midgard/layout/Container/Container.js
src/midgard/layout/NavBar/NavBar.js
src/midgard/layout/NavBar/NavBarConstants.js
src/midgard/layout/TopBar/TopBar.js
src/midgard/redux/authuser/sagas/authuser.saga.js
src/midgard/routes/routesConstants.js
src/styles.scss

Tentative dashboard page with header and Navigation. 
The Items in the dashboard will progress with the features to be developed.
https://github.com/TransparentPath/buildly-react-template/issues/7

Initial dashboard

---

package.json
src/App.js
src/midgard/components/MapComponent/MapComponent.js
src/midgard/components/Table/Table.js
src/midgard/layout/Container/Container.js
src/midgard/layout/TopBar/TopBar.js
src/midgard/pages/Profile/Profile.js
src/midgard/utils/utilMethods.js
src/styles.scss
src/styles/theme.js

1.Tentative dashboard ui with mock tables and map.
2. Added logout option in top bar menu under my account icon.
3. Added generic table component and added react-google-maps library
https://github.com/TransparentPath/buildly-react-template/issues/7

Dashboard components

---

docs/features/index.rst
docs/features/reset_password.rst

Reset password FE documentation
#21

Reset password FE documentation

---

src/midgard/components/MapComponent/MapComponent.js
src/midgard/pages/SensorsGateway/forms/AddSensors.js
src/midgard/pages/Shipment/Shipment.js
src/midgard/pages/Shipment/ShipmentConstants.js
src/midgard/pages/Shipment/components/ShipmentInfo.js
src/midgard/pages/Shipment/components/ShipmentRouteInfo.js
src/midgard/pages/Shipment/components/custodian-info/AddCustodyForm.js
src/midgard/pages/Shipment/components/custodian-info/CustodianInfo.js
src/midgard/redux/custodian/actions/custodian.actions.js
src/midgard/redux/custodian/reducers/custodian.reducer.js
src/midgard/redux/custodian/sagas/custodian.saga.js

1.Frontend break issue fix
2. Add/Edit Custody form

add custody,edit custody form done

---

src/midgard/layout/Container/Container.js
src/midgard/layout/NavBar/NavBar.js
src/midgard/modules/http/http.service.js
src/midgard/pages/Login/Login.js
src/midgard/pages/ResetPassword/NewPasswordForm.js
src/midgard/pages/Shipment/components/ShipmentFilterAndSort.js
src/midgard/redux/authuser/actions/authuser.actions.js
src/midgard/redux/authuser/reducers/authuser.reducer.js
src/midgard/redux/authuser/sagas/authuser.saga.js
src/midgard/utils/utilMethods.js

1.Role based user management screen access.only global admin can access the user management tab
2. Reset password frontend done...

Reset password

---

src/midgard/pages/Shipment/components/ShipmentFilterAndSort.js

Fixes the shipment sort order for most/least recent. Labels were previously incorrect.
#37

Correct labels on shipment sort

---

src/midgard/components/DatePicker/DatePicker.js
src/midgard/components/InlineEditor/InlineEditor.js
src/midgard/components/MapComponent/MapComponent.js
src/midgard/components/PermissionsTable/PermissionsTable.js
src/midgard/components/Slider/RangeSlider.js
src/midgard/components/Table/Table.js
src/midgard/layout/NavBar/NavBar.js
src/midgard/pages/Custodians/forms/AddCustodians.js
src/midgard/pages/Items/Items.js
src/midgard/pages/Items/forms/AddItems.js
src/midgard/pages/Profile/Profile.js
src/midgard/pages/SensorsGateway/forms/AddGateway.js
src/midgard/pages/SensorsGateway/forms/AddSensors.js
src/midgard/pages/Shipment/AlertInfo.js
src/midgard/pages/Shipment/Shipment.js
src/midgard/pages/Shipment/ShipmentConstants.js
src/midgard/pages/Shipment/components/EnvironmentalLimitsInfo.js
src/midgard/pages/Shipment/components/ItemInfo.js
src/midgard/pages/Shipment/components/Sensors&GatewayInfo.js
src/midgard/pages/Shipment/components/ShipmentInfo.js
src/midgard/pages/Shipment/components/ShipmentList.js
src/midgard/pages/Shipment/components/custodian-info/AddCustodyForm.js
src/midgard/pages/Shipment/components/custodian-info/CustodianInfo.js
src/midgard/pages/Shipment/forms/AddDestinationInfo.js
src/midgard/pages/Shipment/forms/AddOriginInfo.js
src/midgard/pages/Shipment/forms/AddShipment.js
src/midgard/pages/Shipment/forms/AddShipperInfo.js
src/midgard/pages/UserManagement/UserGroups/UserGroups.js
src/midgard/pages/UserManagement/UserManagement.js
src/midgard/pages/UserManagement/Users/Users.js

Implements functioning table pagination.
#38

Fix issues with table pagination

---

src/midgard/pages/Shipment/components/ShipmentFilterAndSort.js

Changes the label name to something clearer for user
#45

Change label name from 'Alerts' to 'Alert type'

---

src/midgard/pages/Shipment/components/Sensors&GatewayInfo.js

Allows the user to save multiple sensors without clicking 'save' between each one
#48

Allow user to save multiple sensors at one time

---

src/midgard/pages/Custodians/Custodians.js
src/midgard/pages/Custodians/forms/AddCustodians.js
src/midgard/pages/Dashboard/Dashboard.js
src/midgard/pages/Items/Items.js
src/midgard/pages/Items/forms/AddItems.js
src/midgard/pages/SensorsGateway/Gateway/Gateway.js
src/midgard/pages/SensorsGateway/Sensors/Sensors.js
src/midgard/pages/SensorsGateway/forms/AddGateway.js
src/midgard/pages/SensorsGateway/forms/AddSensors.js
src/midgard/pages/Shipment/Shipment.js
src/midgard/pages/Shipment/components/EnvironmentalLimitsInfo.js
src/midgard/pages/Shipment/components/ItemInfo.js
src/midgard/pages/Shipment/components/Sensors&GatewayInfo.js
src/midgard/pages/Shipment/components/ShipmentInfo.js
src/midgard/pages/Shipment/components/custodian-info/CustodianInfo.js
src/midgard/redux/custodian/actions/custodian.action.test.js
src/midgard/redux/custodian/actions/custodian.actions.js
src/midgard/redux/custodian/sagas/custodian.saga.js
src/midgard/redux/items/actions/items.action.test.js
src/midgard/redux/items/actions/items.actions.js
src/midgard/redux/items/sagas/items.saga.js
src/midgard/redux/sensorsGateway/actions/sensorsGateway.action.test.js
src/midgard/redux/sensorsGateway/actions/sensorsGateway.actions.js
src/midgard/redux/sensorsGateway/sagas/sensorsGateway.saga.js
src/midgard/redux/shipment/actions/shipment.actions.js
src/midgard/redux/shipment/sagas/shipment.saga.js

_To support multi tenancy, filter by organization uuid_
_https://github.com/TransparentPath/buildly-react-template/issues/43_

Add organization filter in GET endpoints

---

src/midgard/pages/Custodians/Custodians.js
src/midgard/pages/Dashboard/Dashboard.js
src/midgard/pages/Dashboard/DashboardConstants.js
src/midgard/pages/Items/Items.js
src/midgard/pages/SensorsGateway/Gateway/Gateway.js
src/midgard/pages/SensorsGateway/Sensors/Sensors.js
src/midgard/pages/Shipment/Shipment.js
src/midgard/pages/Shipment/ShipmentConstants.js
src/midgard/pages/Shipment/components/ShipmentList.js
src/midgard/redux/sensorsGateway/actions/sensorsGateway.actions.js
src/midgard/redux/sensorsGateway/reducers/sensorsGateway.reducer.js
src/midgard/redux/sensorsGateway/sagas/sensorsGateway.saga.js
src/midgard/redux/shipment/sagas/shipment.saga.js

_Show sensor report locations_
_Shipment that is mapped by active gateway returns sensor report that has geographical location of sensors_
_#61_

Sensor report show location data on map

---

src/midgard/pages/Shipment/Shipment.js
src/midgard/pages/Shipment/ShipmentConstants.js
src/midgard/pages/Shipment/components/ShipmentList.js

Make it clearer that you can select a row to display on the map

Better UI for selecting shipment to display on map

---

src/midgard/pages/Shipment/Shipment.js

_Added logic to distinguish new plots by comparing temperature, humidity and lat/long_
_#65_

Modified sensor plot logic

---

src/midgard/layout/TopBar/TopBar.js

_Added refresh button to reload app_
_#67_

Added refresh to reload app

---

src/environments/environment.dev.js
src/environments/environment.js
src/environments/environment.prod.js
src/midgard/modules/oauth/oauth.service.js

_Made session time out configurable as per environment_
_Dev: 1 hour
Prod: 4 hours_
_#75_

Made session timeout configurable from environment

---

src/midgard/pages/Custodians/forms/AddCustodians.js
src/midgard/pages/Shipment/forms/AddDestinationInfo.js
src/midgard/pages/Shipment/forms/AddOriginInfo.js

_Modify ordering of address fields in Custodian form_
_#73_

Updated ordering of country and state in custodian form

---

src/midgard/pages/Shipment/Shipment.js
src/midgard/utils/utilMethods.js

_Show map plots as per selected unit for temperature_
_#71_

Added conversion of unit logic as per selected unit for temperature

---

src/midgard/components/MapComponent/MapComponent.js
src/midgard/pages/Shipment/Shipment.js

Show excursions, warnings, normal colored pins on map.
Change icon color for marker depending on excursion, warnings or normal flags.

colored google markers

---

src/environments/environment.js
src/midgard/hooks/useInput.js
src/midgard/pages/Shipment/Shipment.js
src/midgard/pages/Shipment/components/EnvironmentalLimitsInfo.js
src/midgard/pages/Shipment/components/ShipmentInfo.js
src/midgard/pages/Shipment/forms/AddShipment.js
src/midgard/redux/sensorsGateway/sagas/sensorsGateway.saga.js
webpack.config.js

_To determine if form is updated and show warning popup if user forgets to save_
_#70_

When adding or editing shipments show pop-over if save is not clicked

---

src/midgard/pages/Shipment/AlertInfo.js
src/midgard/redux/shipment/actions/shipment.actions.js
src/midgard/redux/shipment/sagas/shipment.saga.js

Email alerts
Right now only send out email alerts to admins only.

email alerts for admins

---

src/midgard/components/MapComponent/MapComponent.js
src/midgard/pages/Shipment/Shipment.js

_Google maps loading takes significant time and shows blank screen_
_#84_

Google maps loading issue fixed for Shipment 

---

package.json
src/midgard/pages/Shipment/Shipment.js
src/midgard/pages/Shipment/ShipmentConstants.js
src/midgard/pages/Shipment/components/ShipmentSensorTable.js

Sensor report table
Show tabular data for sensor report for a particular shipment.

sensor report table

---

src/midgard/pages/Shipment/ShipmentConstants.js

Add last custody column in custodian data display
Reformat column design as well as add last custody column in the data table for showing custodians in shipment form.

reformat column design, add last custody column

---

src/environments/environment.js
src/environments/environment.prod.js
src/midgard/pages/Dashboard/Dashboard.js
src/midgard/pages/Shipment/AlertInfo.js
src/midgard/pages/Shipment/Shipment.js

_Cleaned up use of shipment flag and corrected session timeout_
_#93_

Cleaned up shipment flag and corrected session timeout

---

src/App.js
src/midgard/layout/Container/Container.js
src/midgard/layout/NavBar/NavBar.js
src/midgard/layout/NavBar/NavBarConstants.js
src/midgard/layout/TopBar/AdminMenu.js
src/midgard/layout/TopBar/TopBar.js
src/midgard/pages/MyAccount/MyAccount.js
src/midgard/pages/Shipment/Shipment.js
src/midgard/pages/Shipment/ShipmentConstants.js
src/midgard/pages/Shipment/components/ItemInfo.js
src/midgard/pages/Shipment/components/Sensors&GatewayInfo.js
src/midgard/pages/Shipment/components/ShipmentSensorTable.js
src/midgard/pages/Shipment/components/custodian-info/AddCustodyForm.js
src/midgard/redux/authuser/sagas/authuser.saga.js

Minor UI Enhancements
Make UI changes/enhancements as per the feedback from the client

minor ui enhancements

---

src/midgard/components/Icons/Icons.js
src/midgard/components/MapComponent/MapComponent.js
src/midgard/pages/Reporting/ReportingConstants.js
src/midgard/pages/Shipment/Shipment.js
src/midgard/pages/Shipment/ShipmentConstants.js
src/midgard/pages/Shipment/components/ShipmentDataTable.js
src/midgard/pages/Shipment/components/ShipmentInfo.js
src/midgard/redux/sensorsGateway/sagas/sensorsGateway.saga.js

_Changes in shipment UI and Map Info window_
_To be merged with Sensor Reports UI changes_
_#105_
closing #105 #106 #107

Shipment UI and Map Info window changes

---

src/midgard/components/MapComponent/MapComponent.js
src/midgard/pages/Shipment/ShipmentConstants.js
src/midgard/pages/Shipment/components/ShipmentDataTable.js

Revert shipment filters as its causing an issue in individual shipment selction

Reverted shipment filters

---

src/midgard/components/MapComponent/MapComponent.js
src/midgard/pages/Profile/Profile.js
src/midgard/pages/Reporting/Reporting.js
src/midgard/pages/Reporting/ReportingConstants.js
src/midgard/pages/SensorsGateway/forms/AddGateway.js
src/midgard/pages/SensorsGateway/forms/AddSensors.js
src/midgard/pages/Shipment/Shipment.js
src/midgard/pages/Shipment/ShipmentConstants.js
src/midgard/pages/Shipment/components/ShipmentDataTable.js
src/midgard/pages/Shipment/components/ShipmentInfo.js
src/midgard/pages/Shipment/components/ShipmentOverview.js
src/midgard/pages/Shipment/components/ShipmentRouteInfo.js
src/midgard/pages/Shipment/components/ShipmentSensorTable.js
src/midgard/pages/Shipment/components/custodian-info/AddCustodyForm.js

_Fix usability bugs encountered in the previous release_
closing #118 
closing #119 
closing #120

Shipment Filters and Map rendering issue fix

---

src/midgard/pages/Reporting/ReportingConstants.js
src/midgard/pages/Shipment/Shipment.js

_Update map aggregation to lat long_

Updated map aggregation to lat long

---

src/midgard/components/GraphComponent/GraphComponent.js
src/midgard/pages/Reporting/ReportingConstants.js
src/midgard/pages/Shipment/Shipment.js
src/midgard/pages/Shipment/components/ShipmentSensorTable.js

_Ordering fixed for sensor report and graph labels fixes_
_#123_
closing #123

Ordering issue fixes for Sensor Report

---

src/midgard/pages/AdminPanel/Configuration/components/OrganizationSettings.js

_Radius configuration in organization settings_
_#125_
closing #125

Radius configuration in organization settings

---

src/midgard/components/MapComponent/MapComponent.js
src/midgard/pages/AdminPanel/Configuration/components/OrganizationSettings.js
src/midgard/pages/Shipment/components/custodian-info/AddCustodyForm.js
src/midgard/pages/Shipment/components/custodian-info/CustodianInfo.js
src/midgard/utils/utilMethods.js

_Show geofence for custodian and allow user to adjust geofence with custody location_
_#126_
closing #126

Render geofence for custodian

---

src/midgard/components/GraphComponent/GraphComponent.js
src/midgard/pages/Reporting/ReportingConstants.js

_Beautification of graph and match with ICLP_
_Added larger domain boundaries to show graph less artistic_
_Removed duplicate timestamps captured on earlier data_
_#130_
closing #130

Added larger domain boundaries to show graph less artistic

---

src/midgard/pages/Shipment/AlertInfo.js

_Corrected mapping of custody_

Corrected mapping of custody

---

src/midgard/redux/shipment/sagas/shipment.saga.js

Form data was not getting updated.
Update the data shown in the shipment info form when edited and saved.

Update shipment form data on save

---

src/midgard/pages/Shipment/AlertInfo.js

_Show custodian name and add alerts when custody matches correctly_

Custody mapping for alerts

---

src/midgard/pages/AdminPanel/ImportExport/forms/AddFromAPI.js
src/midgard/redux/importExport/actions/importExport.actions.js
src/midgard/redux/importExport/sagas/importExport.saga.js

_Added Tive integration devices to gateway_
_#129_
closing #129

Added Tive integration devices to gateway

---

src/midgard/components/GraphComponent/GraphComponent.js
src/midgard/components/MapComponent/MapComponent.js
src/midgard/pages/AdminPanel/Configuration/components/OrganizationSettings.js
src/midgard/pages/Shipment/components/ShipmentRouteInfo.js
src/midgard/pages/Shipment/components/custodian-info/AddCustodyForm.js

_Allow geographical address to be shown instead of co-ordinates_
_#140_
closing #140

Allowed map marker change to show address instead of lat long

---

src/midgard/modules/oauth/oauth.service.js
src/midgard/pages/Shipment/AlertInfo.js
src/midgard/redux/shipment/sagas/shipment.saga.js

_Alert messages do not disappear for a user after they have been acknowledged. Every time a screen is refreshed they all show up again. They should expire._
_#145_
_#143_
closing #145 
closing #143

Alerts session maintenance

---

src/midgard/components/GraphComponent/GraphComponent.js
src/midgard/utils/utilMethods.js

_Fixes for graph rendering_
_Issue in timestamp format. Display was 12 hours instead of 24 hours and data was unsorted_
_#144_
closing #144

Fixes for graph rendering

---

src/midgard/components/MapComponent/MapComponent.js
src/midgard/pages/SensorsGateway/Constants.js
src/midgard/pages/Shipment/ShipmentConstants.js
src/midgard/pages/Shipment/components/Sensors&GatewayInfo.js
src/midgard/pages/Shipment/components/ShipmentInfo.js
src/midgard/redux/shipment/sagas/shipment.saga.js
src/midgard/utils/mock.js

_Integrate tive sensor platform_
_#148_
closing #148

Tive sensor platform integration

---

src/midgard/components/DashboardWrapper/DashboardWrapper.js
src/midgard/pages/Custodians/forms/AddCustodians.js
src/midgard/pages/Items/forms/AddItems.js
src/midgard/pages/SensorsGateway/Constants.js
src/midgard/pages/SensorsGateway/Gateway/Gateway.js
src/midgard/pages/SensorsGateway/Sensors/Sensors.js
src/midgard/pages/SensorsGateway/SensorsGateway.js
src/midgard/pages/SensorsGateway/forms/AddGateway.js
src/midgard/pages/Shipment/components/Sensors&GatewayInfo.js

_Show status field for gateways and link gateway with shipment_
_#149_
closing #149

Patch - Show status field for gateways then show shipment name with a link add that to the list of gateways

---

src/midgard/utils/mock.js

_Enabled Tive sensor platform_

Enabled Tive sensor platform

---

package.json
src/midgard/components/Loader/Loader.js
src/midgard/pages/Shipment/components/PDFViewer.js
src/midgard/pages/Shipment/components/ShipmentInfo.js
src/midgard/pages/Shipment/components/ShipmentKeyInfo.js
src/midgard/pages/Shipment/forms/AddShipment.js
src/midgard/redux/shipment/actions/shipment.actions.js
src/midgard/redux/shipment/reducers/shipment.reducers.js
src/midgard/redux/shipment/sagas/shipment.saga.js

Unique Identifier and PDF upload for a shipment
Allow PDF upload for a shipment as well as the ability to add a unique identifier for a shipment.

Unique Identifier and PDF upload for a shipment

---

src/midgard/pages/Shipment/components/Sensors&GatewayInfo.js

_Corrected usage of platform name to show available gateways as per the shipment platform_
_#155_
closing #155

Rectified platform name for gateway selection

---

src/pages/Custodians/CustodianConstants.js
src/pages/Custodians/forms/AddCustodians.js
src/pages/Items/ItemsConstants.js
src/pages/Items/forms/AddItems.js
src/pages/Reporting/Reporting.js
src/pages/Reporting/ReportingConstants.js
src/pages/SensorsGateway/Constants.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/ShipmentConstants.js
src/pages/Shipment/components/ItemInfo.js
src/pages/Shipment/components/ShipmentInfo.js
src/pages/Shipment/components/custodian-info/AddCustodyForm.js
src/redux/shipment/sagas/shipment.saga.js
src/utils/utilMethods.js

Feedback Fixes and Enhancements.
Make code changes (fixes and enhancements) based on the feedback from the client.

Feedback fixes enhancements

---

src/pages/Shipment/AlertInfo.js
src/pages/Shipment/ShipmentConstants.js
src/pages/Shipment/components/custodian-info/AddCustodyForm.js
src/pages/Shipment/components/custodian-info/CustodianInfo.js
src/utils/utilMethods.js

_Auto order custody while adding and allow user to edit_
_Due to some glitches in setting a shipment 'Completed' once it reaches final custody, the mentioned functionality is removed for now_
_#168_
closing #168

Geofence Alerts - Custody Ordering

---

src/pages/Shipment/AlertInfo.js

_Expire geofence alerts after 24 hours_
_#173_
closing #173

Added expiration time on alerts for 24 hours

---

src/pages/Shipment/components/custodian-info/AddCustodyForm.js

Fix Custodian Form
Custodian Form in Shipment edit not showing Custodian Name. Fix this issue.

fix showing custodian name in the form

---

src/pages/Shipment/components/custodian-info/AddCustodyForm.js

_Custody popup on form submit check validation_

Custody popup on form submit check validation

---

src/pages/Reporting/ReportingConstants.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/ShipmentConstants.js

_Display values coming in from Tive sensor_
_Ensured that both ICLP and Tive sensor values are represented and handled other edge case scenarios_
_#185_
closing #185

Updated the display logic according to tive values

---

src/pages/Reporting/ReportingConstants.js
src/pages/Shipment/Shipment.js

Fix the temperature units for tive
Tive sensors send the temperature in Fahrenheit so no need for temperature conversion here.

Correct temperature units for tive sensors

---

src/pages/AdminPanel/ImportExport/forms/AddFromAPI.js
src/pages/Custodians/Custodians.js
src/pages/Custodians/forms/AddCustodians.js
src/pages/Items/Items.js
src/pages/Items/forms/AddItems.js
src/pages/MyAccount/forms/EditProfileInfo.js
src/pages/Reporting/ReportingConstants.js
src/pages/SensorsGateway/Sensors/Sensors.js
src/pages/SensorsGateway/forms/AddGateway.js
src/pages/SensorsGateway/forms/AddSensors.js
src/pages/Shipment/components/EnvironmentalLimitsInfo.js
src/pages/Shipment/components/ShipmentInfo.js
src/pages/Shipment/components/custodian-info/AddCustodyForm.js
src/pages/Shipment/components/custodian-info/CustodianInfo.js
src/redux/shipment/actions/shipment.actions.js
src/redux/shipment/sagas/shipment.saga.js

Fix bugs and enhancements
Fix bugs and do enhancements as per feedback from customers.

Feedback issues 1

---

src/modules/oauth/oauth.service.js
src/pages/Shipment/AlertInfo.js

Fix Alerts
Fix alerts popup issue. Not showing up.

fix alerts display

---

src/layout/TopBar/TopBar.js
src/pages/AdminPanel/Configuration/ConfigurationConstants.js
src/pages/AdminPanel/Configuration/components/CustodianType.js
src/pages/AdminPanel/Configuration/components/GatewayType.js
src/pages/AdminPanel/Configuration/components/ItemType.js
src/pages/AdminPanel/Configuration/components/Product.js
src/pages/AdminPanel/Configuration/components/ProductType.js
src/pages/AdminPanel/Configuration/components/SensorType.js
src/pages/AdminPanel/Configuration/components/ShipmentFlag.js
src/pages/AdminPanel/Configuration/components/UnitOfMeasure.js
src/pages/Custodians/CustodianConstants.js
src/pages/Reporting/Reporting.js
src/pages/Reporting/ReportingConstants.js
src/pages/Shipment/AlertInfo.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/ShipmentConstants.js
src/pages/Shipment/components/Sensors&GatewayInfo.js
src/pages/Shipment/components/ShipmentDataTable.js
src/pages/Shipment/components/ShipmentInfo.js
src/pages/Shipment/components/ShipmentKeyInfo.js
src/pages/Shipment/components/custodian-info/AddCustodyForm.js
src/redux/options/actions/options.actions.js
src/redux/options/reducers/options.reducer.js
src/redux/shipment/sagas/shipment.saga.js

Feedback bugs and enhancements
Code changes to incorporate bugs or enhancements feedback from the client.

Feedback Bugs and Enhancements - 2

---

src/layout/TopBar/TopBar.js

Change switch to select
Change Timezone switch to a select field in order to allow to add more timezone options in the future.

Change timezone switch to select field

---

src/modules/oauth/oauth.service.js
src/pages/Reporting/Reporting.js
src/pages/Reporting/ReportingConstants.js
src/pages/Reporting/components/AlertsReport.js
src/pages/Shipment/AlertInfo.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/ShipmentConstants.js
src/redux/sensorsGateway/actions/sensorsGateway.actions.js
src/redux/sensorsGateway/actions/sensorsGateway.actions.test.js
src/redux/sensorsGateway/reducers/sensorsGateway.reducer.js
src/redux/sensorsGateway/reducers/sensorsGateway.reducer.test.js
src/redux/sensorsGateway/sagas/sensorsGateway.saga.js
src/redux/shipment/actions/shipment.actions.js
src/redux/shipment/actions/shipment.actions.test.js
src/redux/shipment/reducers/shipment.reducers.js
src/redux/shipment/reducers/shipment.reducers.test.js
src/redux/shipment/sagas/shipment.saga.js

Alerts and Recovery
Change to handle Excursion, Warning and Recovery Alerts.

Excursion, Warning, Recovery Alerts

---

src/pages/Reporting/ReportingConstants.js
src/pages/Reporting/components/AlertsReport.js
src/pages/Shipment/AlertInfo.js
src/redux/sensorsGateway/sagas/sensorsGateway.saga.js

Remove Sensor Alerts logic from FE.
Remove the logic to update shipment and trigger email alerts for Sensor Alerts.

Remove Sensor Alerts logic

---

src/pages/Reporting/ReportingConstants.js
src/pages/Shipment/AlertInfo.js

Integrate test changes
Remove logic for sensor alerts from FE and move to BE. Integrate test and commit final changes.

Remove Sensor Alert 2

---

src/components/Slider/RangeSlider.js
src/layout/TopBar/AccountMenu.js
src/layout/TopBar/AdminMenu.js
src/pages/Shipment/ShipmentConstants.js
src/pages/Shipment/components/EnvironmentalLimitsInfo.js
src/pages/Shipment/components/ItemInfo.js
src/pages/Shipment/components/Sensors&GatewayInfo.js
src/pages/Shipment/components/ShipmentInfo.js
src/pages/Shipment/components/ShipmentKeyInfo.js
src/pages/UserManagement/Users/Users.js

Changes as per feedback.
* On the Items tab of the "Edit Shipment" box (3), the Gross Weight is formatted as $s. Please format as a number w/a comma for thousands.
* Make Slider and Input interactive. If input changes, the slider should change and vice-versa.
* Freeze platform type in edit shipment option as it should not be edited once set to either ICLP or Tive.

Feedback Changes

---

src/pages/SensorsGateway/Constants.js
src/pages/Shipment/ShipmentConstants.js
src/pages/Shipment/components/ShipmentKeyInfo.js
src/redux/shipment/sagas/shipment.saga.js

Allow multiple label value pairs
Allow the user to do the following options.
* Only upload PDF.
* Only add single/multiple label value pair.
* Upload PDF as well as add single/multiple label value pair.

multiple label value pair

---

src/pages/Shipment/Shipment.js
src/pages/Shipment/components/ShipmentDataTable.js
src/pages/Shipment/components/ShipmentInfo.js
src/redux/shipment/sagas/shipment.saga.js

Option to copy completed shipment
Option to copy the following data from the completed shipment.
* Shipment Info (Some parts only)
* Items in the shipment.
* Environmental limits (Temperature and Humidity) for the shipment.

Copy shipment template

---

src/pages/Shipment/components/Sensors&GatewayInfo.js
src/pages/Shipment/components/ShipmentInfo.js
src/pages/Shipment/components/custodian-info/AddCustodyForm.js
src/redux/custodian/sagas/custodian.saga.js
src/redux/shipment/sagas/shipment.saga.js

_Design updates to shipment info screen_
_#232_
closing #232

Updated shipment add/edit screen

---

src/pages/SensorsGateway/Constants.js
src/pages/Shipment/components/Sensors&GatewayInfo.js
src/redux/shipment/sagas/shipment.saga.js

_Updates for gateway updates_
_#242_
closing #242

Updates for assigning Tive Gateways

---

src/layout/TopBar/TopBar.js
src/pages/MyAccount/forms/EditProfileInfo.js
src/redux/authuser/actions/authuser.actions.js
src/redux/authuser/actions/authuser.actions.test.js
src/redux/authuser/sagas/authuser.saga.js

_Allow super admin to update organization_
_#244_
closing #244

Allow super admin to update organization

---

src/redux/shipment/actions/shipment.actions.js
src/redux/shipment/reducers/shipment.reducers.js
src/redux/shipment/sagas/shipment.saga.js

_Refresh shipments once they are edited to indicate status updates_
_#251_
closing #251

Refresh shipments after editing

---

src/pages/Shipment/Shipment.js

_Display sensor reports on initial load_
_#253_

Display sensor reports on initial load

---

src/pages/Shipment/Shipment.js
src/redux/shipment/sagas/shipment.saga.js

_Enroute shipments shown on Active tab_
_#255_
closing #255

Enroute shipments shown on Active tab

---

src/components/MapComponent/MapComponent.js
src/layout/TopBar/TopBar.js
src/pages/Dashboard/Dashboard.js
src/pages/Reporting/Reporting.js
src/pages/Reporting/ReportingConstants.js
src/pages/Reporting/components/SensorReport.js
src/pages/SensorsGateway/Gateway/Gateway.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/components/ShipmentDataTable.js
src/redux/custodian/sagas/custodian.saga.js
src/redux/sensorsGateway/reducers/sensorsGateway.reducer.js
src/redux/shipment/actions/shipment.actions.js
src/redux/shipment/reducers/shipment.reducers.js
src/redux/shipment/sagas/shipment.saga.js

_Rectified logic for switching tabs and persisted aggregate reports_
_Handled issues when switching organization - Re-routes user to Home Page
Allow data persistence for aggregate reports_
_#260_
closing #260

Show aggregate report when switching tabs

---

src/pages/Dashboard/Dashboard.js
src/pages/Reporting/Reporting.js
src/pages/SensorsGateway/Gateway/Gateway.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/components/ShipmentRouteInfo.js
src/redux/custodian/actions/custodian.actions.js
src/redux/custodian/sagas/custodian.saga.js
src/redux/shipment/actions/shipment.actions.js
src/redux/shipment/sagas/shipment.saga.js

Filter custody by shipment

---

src/modules/http/http.service.js
src/pages/Shipment/Shipment.js
src/redux/shipment/sagas/shipment.saga.js

_Error on requesting micro services_
_#265_
closing #265 
@RadhikaPPatel

Fixed error for GCP and custody info on initial load

---

.eslintrc.json
src/pages/Reporting/Reporting.js
src/pages/Reporting/ReportingConstants.js
src/pages/Reporting/components/SensorReport.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/components/Sensors&GatewayInfo.js
src/pages/Shipment/components/ShipmentInfo.js
src/pages/Shipment/components/custodian-info/CustodianInfo.js
src/redux/shipment/sagas/shipment.saga.js
webpack.config.js

_Custodian data persistence on modal refresh_
_#269_
closing #269 
@RadhikaPPatel

Custodian data persistence on modal refresh

---

src/pages/Reporting/Reporting.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/ShipmentConstants.js
src/pages/Shipment/components/Sensors&GatewayInfo.js
src/redux/sensorsGateway/sagas/sensorsGateway.saga.js
src/redux/shipment/sagas/shipment.saga.js
src/utils/mock.js

_Hidden everything that relates to ICLP_
_#271_
closing #271 
@RadhikaPPatel

Hidden everything that relates to ICLP

---

package.json
src/modules/http/http.service.js
src/redux/shipment/actions/shipment.actions.js
src/redux/shipment/reducers/shipment.reducers.js
src/redux/shipment/sagas/shipment.saga.js

_Problems in edit or deleting or creating new shipment_
_Error resolved for any local caching problems_
_Gateway import problem resolved_
_#276_
closing #276 
@RadhikaPPatel

Handle importing gateways and caching problems on Shipment page

---

src/pages/SensorsGateway/Constants.js

_Map gateways to not show newly created shipments with gateways_
_#278_
closing #278

Map gateways to not show newly created shipments with gateways

---

src/components/DataTableWrapper/DataTableWrapper.js
src/pages/AdminPanel/Configuration/Configuration.js
src/pages/AdminPanel/Consortium/ConsortiumSettings.js
src/pages/AdminPanel/ImportExport/ImportExport.js
src/pages/SensorsGateway/Constants.js
src/pages/Shipment/components/Sensors&GatewayInfo.js
src/pages/Shipment/components/ShipmentDataTable.js
src/pages/Shipment/components/ShipmentInfo.js
src/pages/Shipment/forms/AddShipment.js
src/redux/shipment/actions/shipment.actions.js
src/redux/shipment/reducers/shipment.reducers.js

_Fix Generic errors when adding new shipments_
_Filter the "Associate Gateway" dropdown_
_#281_
_#275_
closing #281, #275

Production Issue: Generic errors when adding new shipments and Filter the "Associate Gateway" dropdown

---

src/pages/SensorsGateway/Constants.js
src/redux/custodian/sagas/custodian.saga.js
src/redux/shipment/sagas/shipment.saga.js

Need to redesign the way data is updated for add/edit shipment.
* Check the current bugs on add/edit shipment.
* Redefine the redux-saga flow for add/edit shipment.
Closes #293

Update data on Shipment add/edit - Fetch custody information

---

src/pages/Shipment/components/ShipmentInfo.js

_Allow edit on shipment even if no gateways are attached_

Allow edit even if no gateways are attached

---

src/pages/SensorsGateway/Constants.js
src/pages/Shipment/ShipmentConstants.js
src/pages/Shipment/components/ShipmentDataTable.js
src/pages/Shipment/components/custodian-info/CustodianInfo.js
src/redux/custodian/sagas/custodian.saga.js
src/styles/theme.js

_Work on the feedback recevied after Acceptance testing - v0.4.8_
_#305_
closing #305

Feedback for Acceptance testing - v0.4.8

---

src/pages/AdminPanel/Configuration/Configuration.js
src/pages/AdminPanel/Consortium/ConsortiumSettings.js
src/pages/AdminPanel/ImportExport/ImportExport.js
src/pages/UserManagement/Users/Users.js
src/styles/theme.js

- Fix error form helper text color.
- Fix scroll issue on accordions in admin panel.
- Fix a bug which prevents a user's organization name to be populated after permission or active status update.
Closes #310 & #311.

Admin Panel Scroll Issue & Core User's Organization Name Bug

---

package.json
src/pages/SensorsGateway/Constants.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/ShipmentConstants.js
src/redux/custodian/reducers/custodian.reducer.js
src/redux/custodian/sagas/custodian.saga.js
src/redux/shipment/sagas/shipment.saga.js

_When a custody is added, edited or deleted ensure that the current shipment and other shipments are refreshed with latest data_
_Minor updates on Redux handling_
_#309_
closing #309

Update shipment redux when updates happen on custody

---

src/redux/shipment/sagas/shipment.saga.js

_Show custodian and aggregate report on initial load_
_#321_
closing #321

Show custodian and aggregate report on initial load

---

src/layout/TopBar/TopBar.js
src/pages/AdminPanel/Configuration/Configuration.js
src/pages/AdminPanel/Configuration/components/OrganizationSettings.js
src/pages/Items/forms/AddItems.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/ShipmentConstants.js
src/pages/Shipment/components/ItemInfo.js
src/pages/UserManagement/Users/Users.js
src/redux/custodian/reducers/custodian.reducer.js
src/redux/custodian/sagas/custodian.saga.js
src/redux/items/sagas/items.saga.js
src/redux/shipment/sagas/shipment.saga.js
src/styles/theme.js

_Fixes reported during acceptance testing of v0.5.0_
_#319_
closing #319

UI / UX issues - v0.5.0 fixes

---

src/redux/custodian/reducers/custodian.reducer.js
src/redux/shipment/reducers/shipment.reducers.js

_Fixes for feedback given in v0.5.1 Acceptance testing_
_Adding custody leads to white screen due to redux issue_
_When shipment is cancelled, the status of shipment is not updated_
_#327_
closing #327

Changes in custody and shipment reducer to rectify persistence issue

---

src/pages/Custodians/Custodians.js
src/pages/Custodians/forms/AddCustodians.js
src/pages/Reporting/Reporting.js
src/pages/Shipment/Shipment.js
src/redux/custodian/reducers/custodian.reducer.js
src/redux/custodian/sagas/custodian.saga.js
src/redux/shipment/sagas/shipment.saga.js

_Show sensor report alerts and load all data correctly_
_Fix issues when creating custodian and map it to respective organization_
_Bug fix: Once custodian is deleted, redux is not updated_
_#332_
closing #332

v0.5.2 - Custodian and organization mapping and fetching sensor report alerts

---

src/pages/Reporting/ReportingConstants.js

_Updated columns for Reporting table_
_#334_
closing #334

Updated columns for Reporting table

---

src/redux/options/actions/options.actions.js

_Handle session expiry and redirect user to login page_
_#338_
closing #338

Handle session expiry and redirect user to login page

---

src/pages/SensorsGateway/Constants.js
src/pages/SensorsGateway/forms/AddGateway.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/components/ShipmentInfo.js
src/redux/authuser/sagas/authuser.saga.js
src/redux/custodian/sagas/custodian.saga.js
src/redux/options/actions/options.actions.js
src/redux/shipment/sagas/shipment.saga.js

_Gateway status updates as per attached shipment_
_1. For completed and cancelled shipments, update the gateway status to Available
2. For deleted shipments, update the gateway status to Available
3. Prevent user to update gateways which are assigned to shipment that is either Planned or Enroute_
_#340_
closing #340

Gateway status updates as per attached shipment

---

src/components/DatePicker/DatePicker.js
src/components/TimePicker/TimePicker.js
src/layout/TopBar/TopBar.js
src/pages/SensorsGateway/Constants.js
src/pages/Shipment/CreateShipment.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/components/ShipmentInfo.js
src/utils/mock.js

_Complete the feedback changes requested when creating new shipment_
_Comply with design document_
https://trello.com/c/Gv8w6fYI/170-comply-with-design-document-1-of-8
https://trello.com/c/1rRLn1Pp/171-comply-with-design-document-2-of-8
https://trello.com/c/PMcCB5KF/172-comply-with-design-document-3-of-8
https://trello.com/c/Pvetwdm0/173-comply-with-design-document-4-of-8
https://trello.com/c/2dkNFyka/174-comply-with-design-document-5-of-8
https://trello.com/c/zamDAPB5/176-comply-with-design-document-6-of-8
https://trello.com/c/L19WKzfT/177-comply-with-design-document-7-of-8
https://trello.com/c/mjBHEXwC/178-comply-with-design-document-8-of-8
closing #344
_#344_

Feedback changes for create new shipment worfklow

---

src/components/GraphComponent/GraphComponent.js
src/pages/Reporting/Reporting.js
src/pages/Reporting/ReportingConstants.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/components/ShipmentDataTable.js
src/redux/custodian/sagas/custodian.saga.js
src/redux/sensorsGateway/reducers/sensorsGateway.reducer.js
src/redux/shipment/actions/shipment.actions.js
src/redux/shipment/reducers/shipment.reducers.js
src/redux/shipment/sagas/shipment.saga.js
src/styles/theme.js

_Enhancements to be able to see data for completed and cancelled shipments_
closing #345
closing #346
_#345_
_#346_

Enhancements to be able to see data for completed and cancelled shipments

---

package.json
src/pages/AdminPanel/Consortium/forms/AddConsortium.js
src/pages/Reporting/Reporting.js
src/pages/Shipment/CreateShipment.js
src/pages/Shipment/Shipment.js
src/pages/Shipment/components/ItemInfo.js
src/pages/Shipment/components/Sensors&GatewayInfo.js
src/pages/UserManagement/Users/Users.js
src/redux/items/reducers/items.reducer.js
src/redux/sensorsGateway/reducers/sensorsGateway.reducer.js
webpack.config.js

Fix merge issue
Fix the code to handle the compilation errors for the merge from master to demo
None

Fix merge issue

---

src/pages/PushNotification/PushNotification.js
src/pages/Reporting/Reporting.js
src/pages/Reporting/components/SensorReport.js
src/pages/Shipment/Shipment.js
src/redux/alert/actions/alert.actions.js
src/redux/alert/actions/alert.actions.test.js
src/redux/alert/reducers/alert.reducer.js
src/redux/alert/reducers/alert.reducer.test.js
src/redux/shipment/actions/shipment.actions.js
src/redux/shipment/reducers/shipment.reducers.js
src/redux/shipment/sagas/shipment.saga.js

Fix issues reports in #355 
* Changes made to redux to handle update of shipment data for different operations (get, add, edit, delete).
* Websocket connection set to be retry connection if closed abruptly.
* When a map marker is clicked, highlight only the related first sensor report reading.
Closes #355

Shipment page fixes

---

package.json
src/pages/Reporting/ReportingConstants.js
src/pages/SensorsGateway/Gateway/Gateway.js
src/redux/shipment/sagas/shipment.saga.js

Changes for shock, tilt, battery display in UI
* Shock as last default column in Sensor Report Data table. Hide Battery columns.
* Tilt values to be 'N/A' if no values available from the sensor.
* Get the gateways data every time we fetch shipment list.
Closes #358

Shock, tilt, gateway battery update changes

---

package.json
src/pages/AdminPanel/Configuration/components/OrganizationSettings.js
src/pages/Register/Register.js
src/pages/Reporting/ReportingConstants.js
src/utils/utilMethods.js

Changes for unit of measurements
* While registration, new org needs to set up org default unit of measurement.
* Depending on what unit of measurement is set at the time, handle display of data.
NA

Changes for unit of measurements

---

src/components/MapComponent/MapComponent.js
src/layout/TopBar/TopBarStyles.css
src/layout/TopBar/components/AccountSettings.js
src/layout/TopBar/components/AlertNotifications.js
src/pages/AdminPanel/AdminPanelStyles.css
src/pages/AdminPanel/Configuration/components/OrganizationSettings.js
src/pages/Reporting/Reporting.js
src/pages/Reporting/ReportingStyles.css
src/pages/Reporting/components/AlertsReport.js
src/pages/Reporting/components/SensorReport.js
src/react-query/mutations/shipments/addShipmentMutation.js
src/react-query/mutations/shipments/editShipmentMutation.js

Fix UI issues

---

src/components/CustomizedStepper/CustomizedStepper.js
src/components/CustomizedStepper/CustomizedStepperStyles.css
src/pages/Reporting/Reporting.js
src/pages/Reporting/components/SensorReport.js
src/pages/Shipment/Shipment.js

Fix issues

---

src/layout/TopBar/components/AlertNotifications.js

Fix alert issue in shipment page

---

src/layout/TopBar/components/AlertNotifications.js
src/pages/Reporting/Reporting.js
src/pages/Reporting/components/SensorReport.js
src/pages/Shipment/Shipment.js
src/utils/constants.js

Fix time zone issue in shipment and reporting page.

Fix timezone issue

---

package.json
src/pages/Shipment/CreateShipment.js

Completed to Cancelled, Battery Depleted, Damaged

---

src/layout/TopBar/TopBar.js
src/pages/UserManagement/forms/AddResellers.js

Fix Reseller customer orgs filter

---

src/react-query/queries/shipments/getCountriesQuery.js

Fix some country names in country dropdown.

Fix country names

---

src/pages/Reporting/components/ReportingDetailTable.js

- In the detail reporting table, the order of threshold values needs to be changed.

Fix reporting issue

---

src/pages/Shipment/ShipmentStyles.css

Correct the text field in the "Create Shipment" section.

Fix attached file text field in create shipment section

---

src/pages/Shipment/CustomFileViewer.js

Fix file viewer
